### ISSUE TITLE
Version 1.92 unable to run on my Android 10

### ISSUE THREAD

**Issue by peasoft** [Chainfire/liveboot#14]
I get the error when I run `/data/user_de/0/eu.chainfire.liveboot/files/test`:

```
java.lang.NoSuchMethodException: android.view.SurfaceControl.setSize [int, int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at R.b.m(SourceFile:1)
        at R.b.run(SourceFile:60)
        at V.d.main(SourceFile:42)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
```

1.84 doesn't have the problem.

**Comment by Manamama** [comment]
Similar here. 1.9.2 runs the GUI, installs the script, but the script does not show anything, neither via the GUi test run or during boot. 

The older version, `LiveBoot_1.86_Apkpure.apk` runs fine. 

Specs:
Operating System:
- Name: Android 11 aarch64 OR Linux localhost 4.14.186+ (Termux)
- Kernel: 4.14.186+
- Shell: /data/data/com.termux/files/usr/bin/bash

Hardware:
- Central Processing Unit: MT6785V/CD (8)
- Memory: 3933MiB / 5638MiB
